#!/bin/bash

#rx_name="fixed_vanatta4x2_nostag_006B_006F_006A_006C_x_001A_004A_004B_004D_chest_txfmr_nicktb_siggen_18,5kfc_0,0deg_8bit_pre_16bit_dat_prbs_0,5kbps_usrp_2,5m_depth_005B_purui_tx_93Vrms_22m_22m_1m_foam_sep_purui_rx_1.dat"
rx_name="fixed_vanatta4x2_nostag_006B_006F_006A_006C_x_001A_004A_004B_004D_txfmr_nicktb_18,5kfc_0,0deg_8bit_pre_16bit_dat_prbs_0,5kbps_usrp_2,5m_depth_005B_purui_tx_60Vrms_22m_22m_1m_foam_sep_purui_rx_0.dat"
rx_lb_name="dummy.dat"
nsamps=7000000

./run_tx_samples $rx_lb_name $nsamps &

sleep 1

ssh prwang@192.168.10.98 \
"cd pyaudio_test && ./pcie_speed.sh && python jack_record.py --n 7 --nsamps $nsamps $rx_name"

cd ../rx_outputs/River\ PAB2\ Van\ Atta\ 01-10-2023/
wget localhost:8000/$rx_name